// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: src/proto/stream.proto

package stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Src  string `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	Dst  string `protobuf:"bytes,4,opt,name=dst,proto3" json:"dst,omitempty"`
}

func (x *StreamValue) Reset() {
	*x = StreamValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamValue) ProtoMessage() {}

func (x *StreamValue) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamValue.ProtoReflect.Descriptor instead.
func (*StreamValue) Descriptor() ([]byte, []int) {
	return file_src_proto_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamValue) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamValue) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *StreamValue) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *StreamValue) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

type ClientStreamStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientstart string `protobuf:"bytes,1,opt,name=clientstart,proto3" json:"clientstart,omitempty"`
}

func (x *ClientStreamStart) Reset() {
	*x = ClientStreamStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamStart) ProtoMessage() {}

func (x *ClientStreamStart) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamStart.ProtoReflect.Descriptor instead.
func (*ClientStreamStart) Descriptor() ([]byte, []int) {
	return file_src_proto_stream_proto_rawDescGZIP(), []int{1}
}

func (x *ClientStreamStart) GetClientstart() string {
	if x != nil {
		return x.Clientstart
	}
	return ""
}

type ServerStreamStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serverstart string `protobuf:"bytes,1,opt,name=serverstart,proto3" json:"serverstart,omitempty"`
}

func (x *ServerStreamStart) Reset() {
	*x = ServerStreamStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_stream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamStart) ProtoMessage() {}

func (x *ServerStreamStart) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_stream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamStart.ProtoReflect.Descriptor instead.
func (*ServerStreamStart) Descriptor() ([]byte, []int) {
	return file_src_proto_stream_proto_rawDescGZIP(), []int{2}
}

func (x *ServerStreamStart) GetServerstart() string {
	if x != nil {
		return x.Serverstart
	}
	return ""
}

type ClientStreamEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientend string `protobuf:"bytes,1,opt,name=clientend,proto3" json:"clientend,omitempty"`
}

func (x *ClientStreamEnd) Reset() {
	*x = ClientStreamEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_stream_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamEnd) ProtoMessage() {}

func (x *ClientStreamEnd) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_stream_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamEnd.ProtoReflect.Descriptor instead.
func (*ClientStreamEnd) Descriptor() ([]byte, []int) {
	return file_src_proto_stream_proto_rawDescGZIP(), []int{3}
}

func (x *ClientStreamEnd) GetClientend() string {
	if x != nil {
		return x.Clientend
	}
	return ""
}

type ServerStreamEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serverend string `protobuf:"bytes,1,opt,name=serverend,proto3" json:"serverend,omitempty"`
}

func (x *ServerStreamEnd) Reset() {
	*x = ServerStreamEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_stream_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamEnd) ProtoMessage() {}

func (x *ServerStreamEnd) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_stream_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamEnd.ProtoReflect.Descriptor instead.
func (*ServerStreamEnd) Descriptor() ([]byte, []int) {
	return file_src_proto_stream_proto_rawDescGZIP(), []int{4}
}

func (x *ServerStreamEnd) GetServerend() string {
	if x != nil {
		return x.Serverend
	}
	return ""
}

var File_src_proto_stream_proto protoreflect.FileDescriptor

var file_src_proto_stream_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x55, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x74, 0x61, 0x72, 0x74, 0x22, 0x35, 0x0a,
	0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x22, 0x2f, 0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x65, 0x6e, 0x64, 0x22, 0x2f, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x65, 0x6e, 0x64, 0x32, 0xcb, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x45, 0x6e, 0x64, 0x22, 0x00, 0x28, 0x01, 0x12, 0x40, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x38, 0x0a, 0x08, 0x42, 0x69,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_stream_proto_rawDescOnce sync.Once
	file_src_proto_stream_proto_rawDescData = file_src_proto_stream_proto_rawDesc
)

func file_src_proto_stream_proto_rawDescGZIP() []byte {
	file_src_proto_stream_proto_rawDescOnce.Do(func() {
		file_src_proto_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_stream_proto_rawDescData)
	})
	return file_src_proto_stream_proto_rawDescData
}

var file_src_proto_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_proto_stream_proto_goTypes = []any{
	(*StreamValue)(nil),       // 0: proto.StreamValue
	(*ClientStreamStart)(nil), // 1: proto.ClientStreamStart
	(*ServerStreamStart)(nil), // 2: proto.ServerStreamStart
	(*ClientStreamEnd)(nil),   // 3: proto.ClientStreamEnd
	(*ServerStreamEnd)(nil),   // 4: proto.ServerStreamEnd
}
var file_src_proto_stream_proto_depIdxs = []int32{
	0, // 0: proto.StreamService.ClientStream:input_type -> proto.StreamValue
	2, // 1: proto.StreamService.ServerStream:input_type -> proto.ServerStreamStart
	0, // 2: proto.StreamService.BiStream:input_type -> proto.StreamValue
	3, // 3: proto.StreamService.ClientStream:output_type -> proto.ClientStreamEnd
	0, // 4: proto.StreamService.ServerStream:output_type -> proto.StreamValue
	0, // 5: proto.StreamService.BiStream:output_type -> proto.StreamValue
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_stream_proto_init() }
func file_src_proto_stream_proto_init() {
	if File_src_proto_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_proto_stream_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StreamValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_stream_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ClientStreamStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_stream_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ServerStreamStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_stream_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ClientStreamEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_stream_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ServerStreamEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_stream_proto_goTypes,
		DependencyIndexes: file_src_proto_stream_proto_depIdxs,
		MessageInfos:      file_src_proto_stream_proto_msgTypes,
	}.Build()
	File_src_proto_stream_proto = out.File
	file_src_proto_stream_proto_rawDesc = nil
	file_src_proto_stream_proto_goTypes = nil
	file_src_proto_stream_proto_depIdxs = nil
}
